enum class TokenType {
    LET_KEYWORD,
    STRING_TYPE,
    NUMBER_TYPE,
    TYPE_ASSIGNATION,
    IDENTIFIER,
    ASSIGNATION,
    STRING_LITERAL,
    NUMBER_LITERAL,
    SEMICOLON,
    OPERATOR,
    COMPARE_OPERATOR,
    NULL_TYPE,
}