@startuml
frame "Open" {
    component Libs
    component Common
}

frame "Closed" {
    component Runner
    component Token
    component AST
    component Linter
    component Lexer
    component Parser
    component Interpreter
    component Formatter
    component Factory
    component CLI
}
CLI --> Factory
Factory ---> Linter
Factory -> Formatter
Factory --> Runner
Runner --> Lexer
Runner --> Parser
Runner --> Interpreter
Linter --> AST
Interpreter --> AST
Parser --> AST
Parser --> Token
Formatter ---> Token
Lexer ---> Token

Open <-down- Closed

@enduml