/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "printScript"

include(":ast")
findProject(":ast")?.name = "ast"
include(":token")
findProject(":token")?.name = "token"
include(":interpreter")
findProject(":interpreter")?.name = "interpreter"
include(":parser")
findProject(":parser")?.name = "parser"
include(":lexer")
findProject(":lexer")?.name = "lexer"
include("formatter")
findProject(":formatter")?.name = "formatter"
include(":linter")
findProject(":linter")?.name = "linter"
include(":cli")
findProject(":cli")?.name = "cli"
include("factories")
include("factory")
include("libs")
include("common")
include("runner")
