/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("buildlogic.kotlin-common-conventions")
    jacoco
    `java-library`
}


tasks {
    jacocoTestReport {
        reports {
            xml.required.set(true)
            html.required.set(true)
        }
    }
    jacocoTestCoverageVerification {
        violationRules {
            rule {
                limit {
                    counter = "LINE"
                    value = "COVEREDRATIO"
                    minimum = 0.95.toBigDecimal()
                }
            }
        }
    }

    "check" {
        dependsOn("test")
        dependsOn("jacocoTestCoverageVerification")
        dependsOn("jacocoTestReport")
    }

    "jacocoTestCoverageVerification" {
        dependsOn("test")
    }
}
